ALTER TYPE "public"."kyc_status" RENAME TO "status";--> statement-breakpoint
CREATE TABLE "advertiser" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "advertiser_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"brand_name" text NOT NULL,
	"brand_website" text NOT NULL,
	"brand_logo" text NOT NULL,
	"brand_description" text NOT NULL,
	"status" "status" DEFAULT 'pending' NOT NULL,
	"status_updated_at" timestamp,
	"status_updated_by" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
ALTER TABLE "advertiser" ALTER COLUMN "status" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "advertiser" ALTER COLUMN "status" SET DEFAULT 'pending'::text;--> statement-breakpoint
ALTER TABLE "kyc" ALTER COLUMN "status" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "kyc" ALTER COLUMN "status" SET DEFAULT 'pending'::text;--> statement-breakpoint
DROP TYPE "public"."status";--> statement-breakpoint
CREATE TYPE "public"."status" AS ENUM('pending', 'approved', 'rejected');--> statement-breakpoint
ALTER TABLE "advertiser" ALTER COLUMN "status" SET DEFAULT 'pending'::"public"."status";--> statement-breakpoint
ALTER TABLE "advertiser" ALTER COLUMN "status" SET DATA TYPE "public"."status" USING "status"::"public"."status";--> statement-breakpoint
ALTER TABLE "kyc" ALTER COLUMN "status" SET DEFAULT 'pending'::"public"."status";--> statement-breakpoint
ALTER TABLE "kyc" ALTER COLUMN "status" SET DATA TYPE "public"."status" USING "status"::"public"."status";--> statement-breakpoint
ALTER TABLE "kyc" ALTER COLUMN "id" SET DATA TYPE integer USING id::integer;--> statement-breakpoint
ALTER TABLE "kyc" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "kyc_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "advertiser" ADD CONSTRAINT "advertiser_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "advertiser" ADD CONSTRAINT "advertiser_status_updated_by_user_id_fk" FOREIGN KEY ("status_updated_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;