ALTER TABLE "advertiser" ADD CONSTRAINT "advertiser_user_id_unique" UNIQUE("user_id");
CREATE TYPE "public"."activity" AS ENUM('active', 'paused', 'ended');--> statement-breakpoint
CREATE TABLE "campaign" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campaign_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_by" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"steps" text[] NOT NULL,
	"requirements" text[] NOT NULL,
	"payout_per_user" integer NOT NULL,
	"total_cost" integer NOT NULL,
	"total_slots" integer NOT NULL,
	"image" text,
	"estimated_time" text NOT NULL,
	"status" "status" DEFAULT 'pending' NOT NULL,
	"activity" "activity" DEFAULT 'active' NOT NULL,
	"status_updated_at" timestamp,
	"status_updated_by" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "campaign_rating" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campaign_rating_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"campaign_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"rating" integer NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "campaign_view" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campaign_view_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"campaign_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"advertiser_id" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "submission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "submission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"campaign_id" integer NOT NULL,
	"created_by" text NOT NULL,
	"status" "status" DEFAULT 'pending' NOT NULL,
	"status_updated_at" timestamp,
	"status_updated_by" text,
	"proof_type" text NOT NULL,
	"proof_url" text,
	"proof_text" text,
	"notes" text,
	"advertiser_feedback" text,
	"advertiser_rating" integer,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
ALTER TABLE "advertiser" DROP CONSTRAINT "advertiser_user_id_user_id_fk";
--> statement-breakpoint
ALTER TABLE "campaign" ADD CONSTRAINT "campaign_created_by_advertiser_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."advertiser"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign" ADD CONSTRAINT "campaign_status_updated_by_user_id_fk" FOREIGN KEY ("status_updated_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_rating" ADD CONSTRAINT "campaign_rating_campaign_id_campaign_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaign"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_rating" ADD CONSTRAINT "campaign_rating_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_view" ADD CONSTRAINT "campaign_view_campaign_id_campaign_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaign"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_view" ADD CONSTRAINT "campaign_view_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_view" ADD CONSTRAINT "campaign_view_advertiser_id_advertiser_user_id_fk" FOREIGN KEY ("advertiser_id") REFERENCES "public"."advertiser"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submission" ADD CONSTRAINT "submission_campaign_id_campaign_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaign"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submission" ADD CONSTRAINT "submission_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submission" ADD CONSTRAINT "submission_status_updated_by_user_id_fk" FOREIGN KEY ("status_updated_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "advertiser" ADD CONSTRAINT "advertiser_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint