CREATE TABLE "payment_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payment_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" text NOT NULL,
	"event_type" text NOT NULL,
	"transaction_id" integer,
	"user_id" text,
	"amount" integer,
	"payload" jsonb NOT NULL,
	"created_at" timestamp NOT NULL
);
--> statement-breakpoint
ALTER TABLE "platform_settings" ADD COLUMN "withdrawal_fee" integer;--> statement-breakpoint
ALTER TABLE "payment_log" ADD CONSTRAINT "payment_log_transaction_id_transaction_id_fk" FOREIGN KEY ("transaction_id") REFERENCES "public"."transaction"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_log" ADD CONSTRAINT "payment_log_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;