CREATE TYPE "public"."permission" AS ENUM('view_users', 'manage_users', 'view_kyc', 'manage_kyc', 'manage_wallets', 'view_advertisers', 'manage_advertisers', 'view_campaigns', 'manage_campaigns', 'view_payouts', 'manage_payouts', 'view_settings', 'manage_settings', 'view_admins', 'manage_admins', 'super_admin', 'assign_super_admin');--> statement-breakpoint
CREATE TABLE "admin_roles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"admin_id" text NOT NULL,
	"permissions" "permission"[] NOT NULL,
	"name" text NOT NULL,
	"created_by" text NOT NULL,
	"updated_by" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
ALTER TABLE "admin_roles" ADD CONSTRAINT "admin_roles_admin_id_admin_user_id_fk" FOREIGN KEY ("admin_id") REFERENCES "public"."admin_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_roles" ADD CONSTRAINT "admin_roles_created_by_admin_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."admin_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_roles" ADD CONSTRAINT "admin_roles_updated_by_admin_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."admin_user"("id") ON DELETE no action ON UPDATE no action;